### ISSUE TITLE
invalid LOC header - Zip64 location headers

### ISSUE THREAD

**Issue by Mrucznik** [Velocidex/c-aff4#41] opened 2018-10-26 11:22 UTC
Hello
When I try to read aff4 images created by winpmem tool, using [aff4-java](https://github.com/aff4/aff4-java) library, i get this error:

> [ERROR] 00:04.393(Containers.java:getResourceID:136) invalid LOC header (bad signature)
> java.util.zip.ZipException: invalid LOC header (bad signature)
> at java.util.zip.ZipFile.read(Native Method)
> at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
> at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734)
> at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
> at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
> at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
> at java.io.InputStreamReader.read(InputStreamReader.java:184)
> at java.io.Reader.read(Reader.java:140)
> at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2369)
> at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2348)
> at org.apache.commons.io.IOUtils.copy(IOUtils.java:2325)
> at org.apache.commons.io.IOUtils.copy(IOUtils.java:2273)
> at org.apache.commons.io.IOUtils.toString(IOUtils.java:1041)
> at com.evimetry.aff4.Containers.getResourceID(Containers.java:132)
> at com.evimetry.aff4.Containers.openContainer(Containers.java:91)
> at com.evimetry.aff4.Containers.open(Containers.java:54)
> at com.evimetry.aff4.examples.Information.main(Information.java:58)
> [ERROR] 00:05.377(Information.java:main:95) org.apache.jena.atlas.RuntimeIOException: java.nio.channels.ClosedChannelException

I have opened an [issue](https://github.com/aff4/aff4-java/issues/3) in this library, and I was told, that is caused by that winpmem's zip implementation is generating invalid Zip64 location headers.

Also i tried to verify this images by [evimetry collector](https://evimetry.com/evimetry-community/), but I also get an error: 
> Error: Unable to verify file Memory-3.1.aff4 due to error:
> The first file entry in the container is missing file length information

Could you fix that or propose a solution how to read this aff4 images using java?

**Comment by scudette** [comment] 2018-10-28 13:53
This is probably an issue with Java's Zip implementation. The Zip files that c-aff4 produces are valid and can be read by implementations from python, go and unzip -t also validates them.

I am unsure why Java is having trouble with the LOC header. If you google this error it seems to happen all the time when tools create zip files which do follow the Zip64 spec but fall outside the very narrow implementation that java provides.

I would like to hear more information about why c-aff4's zip is considered invalid? We are following the zip64 app note specs.

**Comment by scudette** [comment] 2018-10-28 14:30
Just to provide more information. I tried to simply decompress the zip file with java and openjdk and it raised an error:

java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor

This is obviously nonsense since it will be impossible to store large uncompressed segments in volumes larger than 4gb without an extended descriptor (The extended descriptor is used to store both the file size and the relative offset to the local header - both of these can be larger than 4gb for stored uncompressed files). Note that when winpmem stores an image in RAW format this happens all the time: The raw image is stored uncompressed inside a zip file and the raw image might be large.

While we might be able to work around some of these limitations the problem is mainly with Java's naive Zip file implementation.

**Comment by scudette** [comment] 2018-11-05 23:47
I am going to close this issue as a Java bug. Please reopen if you feel there is something we can do about it here.

**Closed by scudette** 2018-11-05 23:47 UTC
