### ISSUE TITLE
winpmem.exe map dumping uses a wildly fluctuating amount of memory

### ISSUE THREAD

**Issue by justfalter** [Velocidex/c-aff4#54] opened 2018-11-05 20:35 UTC
While executing `winpmem.exe --format map --output foo.aff4`, I noticed that the memory utilization jumps up and down between 20-50 MB of RAM. When dumping in raw mode, winpmem.exe tends to sit right around ~1.4MB of RAM, only fluctuating +/- 20 KB.

The wild fluctuation appears to be due, in part, to `AFF4Status WinPmemImager::WriteMapObject_()` re-declaring of a 1MB buffer over and over again. This is compounded upon by the design of the AFF4Stream::Read interface: `virtual std::string Read(size_t length);`, which requires any implementation to create and return a new buffer. Naive implementations of `AFF4::ReadBuffer` simply call `auto result = Read(*length);`, causing an additional allocation of a potentially large buffer. 

I have the following observations:
* The constant allocation/deallocation of memory increases the chances of forensic data loss.
* The 1MB buffer as used by WriteMapObject_, to me, seems overly large. When it comes to writing to disk, it has been my experience that there's little benefit to a buffer size beyond ~80KB.
* When it comes to data buffers, it has been my experience that they should be caller-allocated. The caller is then left with the option of re-using the same buffer for subsequent calls, which are likely to occur when reading large quantities of data. This would mean eliminating `AFF4Stream::Read` in favor of `AFF4Stream::ReadBuffer`.

**Comment by scudette** [comment] 2018-11-05 22:59
The main reason memory is fluctuating is because AFF4 Map uses bevies to store the backed data. The bevy is a single Zip segment by default about 10mb large which contains compressed chunks back to back. As the bevy fills up the memory is claimed, then when the bevy is written to disk the memory is freed.

Most modern heap implementations do not mind free and malloc loops - it does not matter too much. Why do you think it is bad? The same memory is just returned and reallocated immediately. 

We use a 1MB read buffer because we want to minimize the userspace/kernelspace transition which (on windows at least) is very expensive. Additional kernel calls need to allocate IRPs and transition into kernel space - so we try to make buffers larger to minimize this. Have you tried to reduce this size to 80kb and measure the overall acquisition time and system load? I am happy to reduce this buffer size if it makes no difference. 

There is an overload of Read() with caller allocated buffers, we could refactor the code to implement that overload and just allocate buffers for the existing overload. I just never bothered to do this because I am not convinced this makes a measurable difference. The driver currently uses buffered io so it writes the data to a system buffer which is then copied by the system to the userspace buffer anyway (so there is on copy which is unavoidable). I think ultimately the bottleneck is the io or compression so the extra copying might not buy much (happy to be proven wrong though :-).

**Comment by scudette** [comment] 2018-11-05 23:50
This issue is similar to #30

**Comment by scudette** [comment] 2018-11-10 06:29
Just checking this issue again, I can not see the allocations you are referring to in WinPmemImager::WriteMapObject_. From my reading of the code we allocate the buffer for each run on the stack (not many runs and its a stack allocation). Then we call ReadBuffer() on the device stream. Typically that will be a FileBackedObject which has a concrete implementation for ReadBuffer (which does not do any copying).

We then call data_stream->Write() the buffer. The data stream is the backing URN of the map (which is an AFF4Image object. There is probably some improvement to be made in AFF4Image::Write() actually: It seems to copy the data buffer twice - once into an internal buffer which it reallocates, then it splits the read into chunks and enques them on the threadpool. I guess we can do something better with the copy but its needed in order to join small writes together.

I tried acquiring an image and the memory of the process fluctuates between about 9mb and 46mb. This actually seems correct - the Bevy is actually 32mb because it is has 1024 chunks of 32kb each. As the image is read we queue the bevy in memory then flush it to disk when its full and start with a new bevy. So I think this is WAI.

**Comment by scudette** [comment] 2019-05-31 12:46
This code had been refactored and probably the issue is not relevant. 

Closing due to age.

**Closed by scudette** 2019-05-31 12:46 UTC
